runtime: python38

entrypoint: gunicorn -b :$PORT --timeout 75 main:app

env_variables:
  OPENAI_API_KEY: " "
  OPENAI_MODEL_ENGINE: "text-davinci-003"

instance_class: B8
manual_scaling:
  instances: 10

service: sacralai5



